### ISSUE TITLE
Pallets not spawning

### ISSUE THREAD

**Issue by Krancisco** [w33zl/FS25_PowerTools#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 
 - Mod Version [e.g. 1.0.0.0]: 
 - Type of game client [e.g. Steam, Giants]: 
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: 
 - Are you the host (if multiplayer) [yes/no]: 

**Additional context**

**Comment by w33zl** [comment]
Unfortunately I cannot do any testing based on only one-liners. You need to describe your problem with as much details as possible, that is why I have created the template.
