### ISSUE TITLE
Pallets not spawning

### ISSUE THREAD

**Issue by Krancisco** [w33zl/FS25_PowerTools#11]
**Describe the bug**
When you open the menu and attempt to spawn pallets nothing spawns. Everything else works. 
**To Reproduce**

**Expected behavior**
Open menu, select spawn pallets, pallet spawns 

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 1.3
 - Mod Version [e.g. 1.0.0.0]: 1.0.0.0
 - Type of game client [e.g. Steam, Giants]: steam
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: single
 - Are you the host (if multiplayer) [yes/no]: 

**Additional context**

sorry about that. Hope this one is better

**Comment by w33zl** [comment]
Thanks! Yes, a work around/quick fix is possibly to start the game with the "-cheats" parameter, see issue: https://github.com/w33zl/FS25_PowerTools/issues/2

If that works, next update will fix this permanently without using the work around.
