### ISSUE TITLE
Powertools

### ISSUE THREAD

**Issue by Fscrub25** [w33zl/FS25_PowerTools#12]
Pallets for your power tools don’t drop when you select pallets for any product and occasionally when you use super strength it stops working when you’re playing for long periods of time of time love the mods but please fix mods like theses make the game a lot more enjoyable version 1.3
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 
 - Mod Version [e.g. 1.0.0.0]: 
 - Type of game client [e.g. Steam, Giants]: 
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: 
 - Are you the host (if multiplayer) [yes/no]: 

**Additional context**

**Comment by w33zl** [comment]
@Fscrub25:

A) Is the pallet spawn issue different from issue #2? And if so, in what way?

B) Unless you send me errors in the log or something there is unfortunately nothing I can do with the information "playing for long periods of time".

**Comment by w33zl** [comment]
@Fscrub25 Did you see the questions above?

**Comment by Fscrub25** [comment]
Did you fix the mod yet
