### ISSUE TITLE
PowerTools flight mode issue

### ISSUE THREAD

**Issue by Greg78200** [w33zl/FS25_PowerTools#14]
> **IMPORTANT!** Please be respectful of my time. If you can't be bothered providing relevant details for an issue, do you expect me to be bothered guessing what could be your problem? If you don't provide me with details, there is simply nothing for me to test/reproduce, and then there is no point in submitting a bug report. Try at least to answer the questions below, and preferably give me as much context and details as possible. 

**Describe the bug**
In PowerTools, Flight mode is not working

**To Reproduce**
1. launch PowerTools
2. Activate "Flight Mode"
3. Press E or Q keys to fly/land
4. Nothing happens

**Expected behavior**
Pressing E or Q, I should fly on the map

**Screenshots or log information**
haven't seen anything wrong in the log, except WARNING  : missing l10n 'input_POWERTOOLS_ALTERNATIVE' in mod 'FS25_PowerTools'

**Additional information (please complete the following information):**
 - Game version [1.3]: 
 - Mod Version [1.0.0.0]: 
 - Type of game client [Steam]: 
 - Do you play single or multiplayer [Singleplayer]: 

**Additional context**
no additional context

**Comment by w33zl** [comment]
This behavior is by design, i.e. it follows the same pattern/design as in the built-in flight command and also same as in previous FS versions. @Greg78200 You should be able to activate flight with the "J" (default) key. Can you please confirm that this works?

With that said, I do agree that you expect the flight mode to be activated directly so this will be improved in the next release.

**Comment by Greg78200** [comment]
@w33zl , I've just tried with the J key, it doesn't make me fly. It disables the flight mode.
No problem with having to press a key to fly (it worked that way in FS22, so, no problem for me)

**Comment by w33zl** [comment]
What happens if you first press J to disable flight and after that press J again, does Q/E then work?

**Comment by w33zl** [comment]
I also recall that in FS22 there were some specific language versions (not sure which) that had different keys than Q/E, maybe you could try "all" keys just to so if you get any response?

**Comment by Greg78200** [comment]
@w33zl , I've tried just a few minutes. So, When I activate the PowerTools, I choose flight mode, and Q/E does anything.
If I press J, it activates the flight mode, and the, A key makes me fly, and E key makes me land. Don't remember if it worked like that in FS22 but, hey, it works :p
The A/E key combination might be due do the fact that here, in France, we are AZERTY keyboards.
Thanks for your tips and advices for the different tries.
