### ISSUE TITLE
[PowerTools] Warning: Failed to register main key for PowerTools

### ISSUE THREAD

**Issue by CrankyAnt** [w33zl/FS25_PowerTools#19]
**WHAT IS THE PROBLEM?**
> When usng the "Fill vehicle"option this error is produced in the log ([PowerTools] Warning: Failed to register main key for PowerTools) and the vehicle is not filling with the selected filltype. 

**HOW CAN I REPRODUCE THE ERROR?**
> get on multiplayer, admin or non-admin as far as i can see no difference. Then fill a random trailer with the powertools option. 

**Screenshots or log information**
log updates only on occasion when on multiplayer so i added the screenshot with the last lines, attached logfile is from 30 minutes earlier but can be used to gain other info. 
[log.txt](https://github.com/user-attachments/files/18136649/log.txt)

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 1.4
 - Mod Version [e.g. 1.0.0.0]: latest 1.0.0.0
 - Type of game client [e.g. Steam, Giants]: giants
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: multiplayer
 - Are you the host (if multiplayer) [yes/no]: yes (dedicated)

**Additional context**
![image](https://github.com/user-attachments/assets/60f144cf-3ffa-406a-92f8-98b83d52ba5f)

**Comment by w33zl** [comment]
Hi, thanks for a clear error report. Yes, this is for sure an issue related to dedicated servers.

**Comment by MaggzWOT** [comment]
This issue is present for me in normal game mode as well. I do not play on a dedicated server but have still been seeing this since at least 1.4.0.0 release

**Comment by w33zl** [comment]
@CrankyAnt Can you please update to the [latest version (1.0.1)](https://www.farming-simulator.com/mod.php?mod_id=303451&title=fs2025) and see if this is resolved?

**Comment by CrankyAnt** [comment]
> @CrankyAnt Can you please update to the [latest version (1.0.1)](https://www.farming-simulator.com/mod.php?mod_id=303451&title=fs2025) and see if this is resolved?

Tried but getting this error, i believe a duplicate of [20](https://github.com/w33zl/FS25_PowerTools/issues/20) and perhaps [21](https://github.com/w33zl/FS25_PowerTools/issues/21)
```
2024-12-17 15:43 Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/Users/xxxx/OneDrive/Documents/My Games/FarmingSimulator2025/CDDM Farm/FS25_PowerTools/lib/ModHelper.lua:429: attempt to index nil with 'farmId'
```

**Comment by w33zl** [comment]
Thanks. Yes, if you run this on a dedicated server you do need this hotfix instead: https://github.com/w33zl/FS25_PowerTools/releases/tag/v1.0.1-hotfix1

Would be good to know if either the ModHub 1.0.1 or the hotfix version works without those warnings in the log so I can close this ticket (on my end it looks good, but it often does that when developing stuff 🤓).

**Comment by CrankyAnt** [comment]
> Thanks. Yes, if you run this on a dedicated server you do need this hotfix instead: https://github.com/w33zl/FS25_PowerTools/releases/tag/v1.0.1-hotfix1
> 
> Would be good to know if either the ModHub 1.0.1 or the hotfix version works without those warnings in the log so I can close this ticket (on my end it looks good, but it often does that when developing stuff 🤓).

Tried again with that hotfix, now no error in console but also not filling the trailer, tried on a regular trailer and the kubota vehicle. 
The errors in the logfile at the bottom are from when I tried spawning pallets and bales, for bales it says only allowed on server (this was on server and as admin) and pallets seem to spawn but fall through the ground if I saw that correct, my TSSC says I have the amount of beetroot pallets I spawned but they are nowhere to be found.. 
[log.txt](https://github.com/user-attachments/files/18170235/log.txt)

**Comment by w33zl** [comment]
Thanks. Yes, that is another issue. Currently the pallets are spawned w/o physics if you are not the server, so the fall through the ground :) I will try to figure that out as well, but that is a different issue, this is actually #15.

And the trailer is also related to you not being the server, I will create a separate issue (#23) for this and have a look at it. 

For now, I will consider this above warning in the log to be resolved.
