### ISSUE TITLE
Spawning pallets doesn't work

### ISSUE THREAD

**Issue by w33zl** [w33zl/FS25_PowerTools#2]
**Problem:** 
When trying to spawn pallets, nothing happens and/or you get an message in the log like "gsPalletAdd ... command not found".

![image](https://github.com/user-attachments/assets/36cf1eec-2213-4fde-84c3-822d7878992e)

**Reason:** 
This command relies on base game functionality that is disable if you are not using the `-cheats` startup parameter. 

**Solution:** 
This will be amended in next release.

**Work around:** 
Start the game with the cheats parameter, e.g. `FarmingSimulator2025Game.exe -skipStartVideos -cheats`

**Comment by Krancisco** [comment]
How do I go about starting the game with the cheats parameter

**Comment by w33zl** [comment]
> How do I go about starting the game with the cheats parameter

Follow this guide, just add `-cheats` after the `-skipStartVideos` part:
https://youtu.be/87KLHgMgTiM?si=QTwDy8SZxCFE83JP&t=125

**Comment by pixelinkmedia** [comment]
I have the same issue.
If I select a Palette from the selector and click on the OK button....
It doesn't load any palette and the selector default to red beets.
This doesn't work for ALL palettes
However, I can spawn bales fine

**Comment by w33zl** [comment]
@pixelinkmedia @Krancisco Can any of you verify that the latest version (v1.0.1) solved this issue?

**Comment by Krancisco** [comment]
> @pixelinkmedia @Krancisco Can any of you verify that the latest version (v1.0.1) solved this issue?

Yes it works now without using the -cheat parameter.  Thank you.

**Comment by w33zl** [comment]
@Krancisco Thanks!

**Comment by pixelinkmedia** [comment]
Yes, its works. THANK YOU!!
