### ISSUE TITLE
After Update Can't Login to Dedicated Server

### ISSUE THREAD

**Issue by Sirmitch255** [w33zl/FS25_PowerTools#21]
> **IMPORTANT!** Please be respectful of my time. If I don't get enough and/or specific details I really cannot investigate the issue. Please answer the questions below to the best of your ability, providing as much details and context as possible. 

**WHAT IS THE PROBLEM?**
> _A clear and concise description of what the bug is._
Updated the mod then when loading into dedicated server only loads to 57% and freezes. I then unactivated the powertools mod on the server and was able to load into the server just fine.

**HOW CAN I REPRODUCE THE ERROR?**
> E.g. first go to X, then do Y. The more details I get the greater is the chance that I can solve the issue.
Add mod to a dedicated server and try to load into the server.

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 1.4.0.0
 - Mod Version [e.g. 1.0.0.0]: 1.0.1.0
 - Type of game client [e.g. Steam, Giants]: Steam
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: Multiplayer
 - Are you the host (if multiplayer) [yes/no]: Dedicated server on my own box

**Additional context**

**Comment by PARADOX070** [comment]
Same issue on our dedicated. Also reported on Giants: https://forum.giants-software.com/viewtopic.php?t=211457

**Comment by PARADOX070** [comment]
> Can you please check if this hotfix amends the issue? https://github.com/w33zl/FS25_PowerTools/releases/tag/v1.0.1-hotfix1

Working again cheers!

**Comment by w33zl** [comment]
Perfect, thanks for letting me know.

**Comment by Ovolonishi** [comment]
Hi

The powertools mod can't be installed anymore in fs25 self, is it removed?
It also doesn't work when I download the file and do it manually.

**Comment by Sirmitch255** [comment]
Thank you @w33zl ! Super Fast Response!

**Comment by w33zl** [comment]
> Hi
> 
> The powertools mod can't be installed anymore in fs25 self, is it removed? It also doesn't work when I download the file and do it manually.

Not removed, it is still there. Have you updated the game to the 1.4 version?

**Comment by Ovolonishi** [comment]
How can I see what version the game is on? I play on steam. 

"installed content update: Nov 28. 2024 at 8:46 PM"

**Comment by Ovolonishi** [comment]
> > Hi
> > The powertools mod can't be installed anymore in fs25 self, is it removed? It also doesn't work when I download the file and do it manually.
> 
> Not removed, it is still there. Have you updated the game to the 1.4 version?

hi
How can I see what version the game is on? I play on steam.

"installed content update: Nov 28. 2024 at 8:46 PM"

**Comment by w33zl** [comment]
@Ovolonishi I opened a separate ticket because I think this is something else. Please see #24
