### ISSUE TITLE
Mod is missing after latest update

### ISSUE THREAD

**Issue by w33zl** [w33zl/FS25_PowerTools#24]
Hi

The powertools mod can't be installed anymore in fs25 self, is it removed?
It also doesn't work when I download the file and do it manually.

_Originally posted by @Ovolonishi in https://github.com/w33zl/FS25_PowerTools/issues/21#issuecomment-2549747571_

**Comment by w33zl** [comment]
@Ovolonishi Can you please send me your log.txt. Without the details of the log there is really nothing I can do.

**Comment by Ovolonishi** [comment]
> @Ovolonishi Can you please send me your log.txt. Without the details of the log there is really nothing I can do.

[log.txt](https://github.com/user-attachments/files/18177480/log.txt)

**Comment by Ovolonishi** [comment]
Just found out that i'm on version 1.3.0.0

**Comment by Ovolonishi** [comment]
Hi,

I updated the game. I needed to restart my pc before it showed.
Its fixed now.
Thanks for the Help!

**Comment by w33zl** [comment]
Great, I'm happy that it was resolved that easily :)
