### ISSUE TITLE
This mod is not working for me even if I change it from f12 to f9. In fs22 I have it on f9 and it works

### ISSUE THREAD

**Issue by tierpmaskin** [w33zl/FS25_PowerTools#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or log information**
If applicable, add screenshots and/or errors and warnings from your log.txt to help explain your problem.

**Additional information (please complete the following information):**
 - Game version [e.g. v1.3]: 
 - Mod Version [e.g. 1.0.0.0]: 
 - Type of game client [e.g. Steam, Giants]: 
 - Do you play single or multiplayer [Singleplayer/Multiplayer]: 
 - Are you the host (if multiplayer) [yes/no]: 

**Additional context**

**Comment by w33zl** [comment]
Can you please provide some information for me to investigate? E.g. see (unanswered) questions above in the ticket. Please also provide screenshot of your control bindings, the log file, list of active mods and other information that can be helpful for me to reproduce the issue.

**Comment by w33zl** [comment]
@tierpmaskin Any updates on the issue?

**Comment by tierpmaskin** [comment]
> @tierpmaskinNågra uppdateringar om problemet?

Har fortfarande problem med det

**Comment by w33zl** [comment]
@tierpmaskin Did you see my first comment?

**Comment by w33zl** [comment]
This is probably a key binding conflict with another mod or base game functionality. Without more information I cannot reproduce the problem.
